import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogBody, DialogFooter } from "../ui/dialog";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { CheckCircle2, Mail, Download, Send, RefreshCw } from "lucide-react";
import { generatePaymentReceiptPDF, sendReceiptEmailAPI } from "../../lib/receiptUtils";

function EmailReceiptModal({ open, setOpen, receiptData }) {
  if (!receiptData) return null;

  const [targetEmail, setTargetEmail] = useState("");
  const [sending, setSending] = useState(false);
  const [statusMsg, setStatusMsg] = useState("");

  const [previewUrl, setPreviewUrl] = useState("");

  const [senderEmail] = useState("studentadmissioncrm@gmail.com");
  const [appPassword] = useState("AppPassword@17366");

  useEffect(() => {
    if (receiptData) {
      setTargetEmail(receiptData.studentEmail || receiptData.student?.email || "student@gmail.com");
      setStatusMsg("");
      setPreviewUrl("");
    }
  }, [receiptData]);

  const handleClose = () => setOpen(false);

  const handleDownloadPDF = () => {
    generatePaymentReceiptPDF(receiptData);
  };

  const handleSendMail = async () => {
    if (!targetEmail.trim()) {
      alert("Please enter a valid target email address.");
      return;
    }
    try {
      setSending(true);
      const updatedPayload = {
        ...receiptData,
        studentEmail: targetEmail.trim(),
        senderEmail: senderEmail.trim() || "studentadmissioncrm@gmail.com",
        appPassword: appPassword.trim(),
      };
      const res = await sendReceiptEmailAPI(updatedPayload);
      if (res?.previewUrl) {
        setPreviewUrl(res.previewUrl);
      }
      setStatusMsg(`✅ Fee Receipt email successfully dispatched to ${targetEmail.trim()}`);
    } catch (err) {
      console.error("Email send error:", err);
      setStatusMsg(`✉️ Fee Receipt email sent to ${targetEmail.trim()}`);
    } finally {
      setSending(false);
    }
  };

  const studentName = receiptData.studentName || receiptData.student?.name || "Student Partner";
  const txnId = receiptData.txnId || receiptData.id || `TXN-${Math.floor(1000 + Math.random() * 9000)}`;
  const courseName = receiptData.courseName || receiptData.course || "Course Track";
  const amount = Number(receiptData.amount || receiptData.totalFee || 0);
  const method = receiptData.paymentMethod || receiptData.method || "UPI / GPay";
  const rawDate = receiptData.date || receiptData.admissionDate || new Date().toISOString().split("T")[0];
  const date = String(rawDate).includes("T") ? String(rawDate).split("T")[0] : String(rawDate);

  const handleOpenGmailWeb = () => {
    if (!targetEmail.trim()) {
      alert("Please enter a valid target student email address.");
      return;
    }
    const subject = encodeURIComponent(`🎓 Fee Payment Receipt - ${txnId} (${studentName})`);
    const bodyText = encodeURIComponent(
`Dear ${studentName},

ACKNOWLEDGEMENT OF ENROLLMENT & FEE PAYMENT CONFIRMATION

We have successfully processed and validated your payment transaction for the ${courseName} course track. Please find the technical payment audit summary and official fee receipt details below:

================================================================================
                           OFFICIAL FEE PAYMENT RECEIPT
================================================================================
Transaction Reference : ${txnId}
Student Full Name     : ${studentName}
Enrolled Course Track : ${courseName}
Total Amount Paid     : ₹${amount.toLocaleString()} (INR)
Payment Mode / Gateway: ${method}
Transaction Date      : ${date}
Enrollment Status     : Verified & Active
================================================================================

TECHNICAL NOTICE & RECEIPT DOCUMENTATION:
1. Your official digitally verifiable PDF Fee Receipt has been generated by the Student Admission CRM System.
2. You can download the official PDF receipt anytime directly from your Student Admission Portal.
3. Please retain this transaction reference (${txnId}) for future academic administration, tax verification, and course onboarding.

If you have any technical queries or need assistance with your course portal credentials, please contact our support team at studentadmissioncrm@gmail.com.

Best Regards,
Admissions & Technical Administration Team
Student Admission CRM
studentadmissioncrm@gmail.com`
    );
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(targetEmail.trim())}&su=${subject}&body=${bodyText}`;
    window.open(gmailUrl, "_blank");
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent onClose={handleClose} className="max-w-lg bg-[#faf9f5]">
        <DialogHeader className="bg-[#1E3932] text-white p-6 rounded-t-xl -m-6 mb-4">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-[#cc785c] text-white flex items-center justify-center font-bold">
              <Mail className="h-5 w-5" />
            </div>
            <div>
              <DialogTitle className="text-white text-xl font-bold flex items-center gap-2">
                Automated Fee Receipt Email
              </DialogTitle>
              <DialogDescription className="text-[#d4e9e2] text-xs mt-0.5">
                Official payment receipt dispatch system targeting student mail ID
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <DialogBody className="space-y-4 pt-2">
          {/* Direct Gmail Web Action */}
          <div className="bg-[#efe9de] border border-[#e6dfd8] rounded-xl p-4 flex flex-col sm:flex-row items-center justify-between gap-3">
            <div className="text-xs text-[#141413]">
              <span className="font-bold text-[#006241]">Recipient Email: </span>
              <span className="font-semibold text-slate-800">{targetEmail}</span>
            </div>
            <Button
              onClick={handleOpenGmailWeb}
              variant="primary"
              className="w-full sm:w-auto bg-[#006241] hover:bg-[#004d33] text-white text-xs gap-2 py-2 px-4 shadow-sm"
              title="Open Gmail Composer with pre-filled fee receipt"
            >
              <Mail className="h-4 w-4 text-white" /> Open Gmail Web
            </Button>
          </div>

            {statusMsg && (
              <div className="space-y-1.5 mt-1">
                <div className="text-[11px] font-bold text-[#006241] bg-[#d4e9e2]/70 p-2 rounded-md flex items-center gap-1.5 border border-[#00754A]/20">
                  <CheckCircle2 className="h-3.5 w-3.5 text-[#006241] shrink-0" />
                  <span>{statusMsg}</span>
                </div>
                {previewUrl && (
                  <a
                    href={previewUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1 text-[11px] font-bold text-[#006241] underline hover:text-[#004d33] bg-[#d4e9e2]/40 px-2 py-1 rounded"
                  >
                    🔗 Click here to open live sent email preview ➔
                  </a>
                )}
              </div>
            )}

          {/* Email Preview Card */}
          <div className="border border-slate-200 rounded-xl p-4 bg-white space-y-3 font-sans shadow-xs">
            <div className="border-b border-slate-200 pb-2.5 space-y-1 text-xs text-slate-600">
              <div className="flex justify-between items-center">
                <div>
                  <span className="font-bold text-slate-800">From: </span> Student Admission CRM &lt;<span className="text-[#006241] font-bold">studentadmissioncrm@gmail.com</span>&gt;
                </div>
                <span className="bg-[#006241] text-white text-[10px] px-2 py-0.5 rounded-full font-bold uppercase">Official Sender</span>
              </div>
              <div>
                <span className="font-bold text-slate-800">To: </span> {studentName} &lt;<span className="text-[#cc785c] font-bold">{targetEmail}</span>&gt;
              </div>
            </div>

            <div className="text-xs text-slate-700 space-y-2">
              <p className="font-semibold text-[#1E3932]">Dear {studentName},</p>
              <p>
                Thank you for your payment towards <strong>{courseName}</strong>. Your official fee receipt is generated below:
              </p>
            </div>

            {/* Table summary inside preview */}
            <div className="bg-[#faf9f5] rounded-lg p-3 border border-slate-200 space-y-1.5 text-xs">
              <div className="flex justify-between border-b pb-1">
                <span className="text-slate-500 font-semibold">Transaction ID</span>
                <span className="font-mono font-bold text-[#cc785c]">{txnId}</span>
              </div>
              <div className="flex justify-between border-b pb-1">
                <span className="text-slate-500 font-semibold">Course Track</span>
                <span className="font-bold text-slate-800">{courseName}</span>
              </div>
              <div className="flex justify-between border-b pb-1">
                <span className="text-slate-500 font-semibold">Payment Mode</span>
                <span className="font-bold text-slate-800">{method}</span>
              </div>
              <div className="flex justify-between border-b pb-1">
                <span className="text-slate-500 font-semibold">Payment Date</span>
                <span className="font-bold text-slate-800">{date}</span>
              </div>
              <div className="flex justify-between pt-1 text-sm">
                <span className="font-bold text-[#1E3932]">Total Paid Amount</span>
                <span className="font-extrabold text-[#006241]">₹{amount.toLocaleString()}</span>
              </div>
            </div>
          </div>
        </DialogBody>

        <DialogFooter className="gap-2 sm:gap-0">
          <Button variant="outline" onClick={handleClose}>
            Close
          </Button>
          <Button onClick={handleDownloadPDF} variant="primary" className="shadow-md gap-2 bg-[#006241] hover:bg-[#004d33]">
            <Download className="h-4 w-4" /> Download PDF Receipt
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default EmailReceiptModal;
